import Head from 'next/head';

import Header from '../components/global/Header';
import Footer from '../components/global/Footer';
import styles from '../styles/Home.module.scss';


import EmployeeList from '../components/about/EmployeeList';
import aboutStyles from '../styles/About.module.scss';

export default function About(){

  return (
    <>
      <Head>
        <title>About Us - AOT Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      <Header styles={ styles } alt={ true }/>

      <main className={ [ styles.main, aboutStyles.main ].join(' ') }>
        <EmployeeList styles={ aboutStyles } />
      </main>

      <Footer styles={ styles }/>

    </>
  );
}