import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Header from '../components/global/Header';
import Footer from '../components/global/Footer';

import Hero from '../components/index/banner/Hero';
import Blurb from '../components/index/banner/Blurb';

import HighlightList from '../components/index/highlights/HighlightList';

import servicesData from '../utils/data/servicesData';

export default function Home() {
  return (
    <>
      <Head>
        <title>AOT Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      
      <div className={ styles.banner }>
        <Header styles={ styles }/>
        <Hero styles={ styles } services={ servicesData }/>
      </div>

      <main className={ styles.main }>
        <HighlightList services={ servicesData }/>
      </main>

      <Footer styles={ styles }/>
    </>
  )
}
