import Head from "next/head";

import Header from "../components/global/Header";
import Footer from "../components/global/Footer";
import styles from '../styles/Home.module.scss';



export default function Rates({}){

  return (
    <>
      <Head>
        <title>Rates - Precision First Therapy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      <Header styles={ styles } alt={ true }/>

      <main className={ [ styles.main ].join(' ') }>
        
      </main>

      <Footer styles={ styles }/>

    </>
  );
}