import Head from 'next/head';
import Header from '../../components/global/Header';
import Footer from '../../components/global/Footer'
import styles from '../../styles/Home.module.scss';

import ServiceHeader from '../../components/services/ServiceHeader';
import ServiceList from '../../components/services/ServiceList';
import serviceStyles from '../../styles/Services.module.scss';


export default function Services(){

  
  return (
    <>
      <Head>
        <title>Services - AOT Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      <Header styles={ styles } alt={ true }/>

      <main className={ styles.main } >

        <ServiceHeader styles={ serviceStyles }/>
        <ServiceList styles={ serviceStyles }/> 
        
      </main>

      <Footer styles={ styles }/>

    </>
  );
}