import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

import Head from 'next/head';
import Header from '../../components/global/Header';
import Footer from '../../components/global/Footer'
import styles from '../../styles/Home.module.scss';

import ServiceHeader from '../../components/services/ServiceHeader';
import ServiceList from '../../components/services/ServiceList';
import serviceStyles from '../../styles/Services.module.scss';

import ServiceFullPage from '../../components/services/ServiceFullPage';
import servicePageStyles from '../../styles/ServicePage.module.scss';

import getServiceData from '../../utils/helpers/api';

export default function Services(){

  // const router = useRouter();
  // const [queryId, setQueryId] = useState(undefined)
  // const [currentService, setCurrentService] = useState(undefined)

  // useEffect(() => {

  //   console.log('ROUTER QUERY::: ', router.query)

  //   if (router.query.id !== queryId){
  //     console.log('QUERY ::: NO QUERYID');
  //     setQueryId(parseInt(router.query.id));
  //   } else if (!router.query.id && queryId){
  //     console.log('NO QUERY ::: QUERYID');
  //     setQueryId(undefined);
  //   }
    
    
  //   if (!currentService && queryId){
  //     console.log('NO SERVICE ::: QUERYID');
  //     getServiceData(queryId, setCurrentService);
  //   } else if ( currentService && (queryId !== currentService.id) ){
  //     console.log('SERVICE ::: QUERYID NOT SERVICE.ID');
  //     getServiceData(queryId, setCurrentService);
  //   } else if ( currentService && !queryId ){
  //     console.log('SERVICE ::: NO QUERYID');
  //     setCurrentService(undefined);
  //   }

  //   console.log('CURRENT:::', currentService)

  // }, [currentService, queryId])

  return (
    <>
      <Head>
        <title>Contact - AOT Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header styles={ styles } alt={ true }/>

      <main className={ styles.main } >

        <ServiceHeader styles={ serviceStyles }/>
        <ServiceList styles={ serviceStyles }/> 
        
      </main>

      <Footer styles={ styles }/>

    </>
  );
}