import { useRouter } from 'next/router';
import { useState, useEffect } from 'react';

import Head from 'next/head';

import Header from '../../components/global/Header';
import Footer from '../../components/global/Footer'
import styles from '../../styles/Home.module.scss';

import ServiceHeader from '../../components/services/ServiceHeader';
import ServiceFullPage from '../../components/services/ServiceFullPage';
import servicePageStyles from '../../styles/ServicePage.module.scss';
import servicesStyles from '../../styles/Services.module.scss';

import getServiceData from '../../utils/helpers/api';

export default function Service(){
  const router = useRouter();
  const [serviceId, setServiceId] = useState(router.query.id);
  const [currentService, setCurrentService] = useState(undefined);

  useEffect(() => {

    console.log('SEVICEID:::', serviceId, '\n', "CUrrent::: ", currentService)
    if (router.query.id){
      if (!serviceId){
        setServiceId(router.query.id)
      }
    }

    if (serviceId && !currentService){
      console.log('here')
      getServiceData(serviceId, setCurrentService)
    }
  },[serviceId, currentService])

  return (
    <>
      <Head>
        <title>Contact - AOT Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inspiration&display=swap" rel="stylesheet"/>
        {/* <link href="https://fonts.googleapis.com/css2?family=Yanone+Kaffeesatz:wght@300&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Jost:wght@300&display=swap" rel="stylesheet"/> */}
        <link href="https://fonts.googleapis.com/css2?family=Catamaran:wght@300&display=swap" rel="stylesheet"/>

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header styles={ styles } alt={ true }/>

      <main className={ styles.main } >
        {/* <ServiceHeader styles={ servicesStyles }/> */}
        { currentService && <ServiceFullPage styles={ servicePageStyles } service={ currentService } />}
      </main>

      <Footer styles={ styles }/>
    </>
  );
}